### ISSUE TITLE
research CSS or react library opportunities.

### ISSUE THREAD

**Issue by atleastitsanethosman** [danshoup/Game-On#1]
Look for opportunities to use either bootstrap or another react or CSS library to handle component construction / formatting.

**Comment by danshoup** [comment]
This library could be a viable front end for managing users and wagers etc.
https://marmelab.com/react-admin/

Also, Material-UI (https://material-ui.com/) could be great for our front end.

There are is also Bootstrap-React library, of course, and there are others, but the above seemed good. Can discuss tomorrow at stand-up.
